In [1]:
import torch
import numpy as np

In [2]:
t = torch.tensor([[1,2,3],[4,5,6]])

#### Rank: number of dim present in a tensor. n Rank means n axis
#### axis length tell us how much index we can use to represent
#### shape

In [3]:
t.shape

torch.Size([2, 3])

In [4]:
t.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
t = torch.Tensor()
type(t)

torch.Tensor

In [6]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [7]:
device = torch.device("cuda:0")
device

device(type='cuda', index=0)

#### tensor have to have the same data type & device incase those two tensors perform some action togather

In [8]:
t1 = torch.tensor([1,2,3])
print("1st tensor dtype:", t1.dtype)

t2 = torch.tensor([1.,2.,3.])
print("1st tensor dtype:",t2.dtype)

1st tensor dtype: torch.int64
1st tensor dtype: torch.float32


In [9]:
# t1 + t2

In [10]:
t1 = torch.tensor([1,2,3])
print("1st tensor device:", t1.device)

t2 = torch.tensor([3,4,5]).cuda()
print("1st tensor device:",t2.device)

1st tensor device: cpu
1st tensor device: cuda:0


In [11]:
# t1 + t2

#### creating tensor

In [12]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

##### 1.

In [13]:
t1 = torch.Tensor(data)
t1

tensor([1., 2., 3.])

##### 2.

In [14]:
t2 = torch.tensor(data)
t2

tensor([1, 2, 3], dtype=torch.int32)

##### 3.

In [15]:
t3 = torch.as_tensor(data)
t3

tensor([1, 2, 3], dtype=torch.int32)

In [16]:
t3 = torch.as_tensor(data, dtype = torch.float64)
t3

tensor([1., 2., 3.], dtype=torch.float64)

##### 4.

In [17]:
t4 = torch.from_numpy(data)
t4

tensor([1, 2, 3], dtype=torch.int32)

##### 5. (some other useful way to create tensor)

In [18]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [19]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [20]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [21]:
torch.rand(2,2)

tensor([[0.1932, 0.6521],
        [0.2036, 0.8483]])

In [22]:
data[0] = 0
data

array([0, 2, 3])

In [23]:
t3

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
t4

tensor([0, 2, 3], dtype=torch.int32)

In [25]:
t1

tensor([1., 2., 3.])

In [26]:
t2

tensor([1, 2, 3], dtype=torch.int32)